[versions]
kotlin = "1.9.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

dokka-gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.20"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.25.3"
assertk = "com.willowtreeapps.assertk:assertk:0.26.1"
