[versions]
kotlin = "1.8.20"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

dokka-gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.8.10"
