[versions]
kotlin = "1.9.20-Beta"
kotlinx-benchmark = "0.4.0"

[libraries]
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-allOpenPlugin = { module = "org.jetbrains.kotlin:kotlin-allopen", version.ref = "kotlin" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }

kotlinx-benchmark-gradlePlugin = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-plugin", version.ref = "kotlinx-benchmark" }
kotlinx-benchmark-runtime = { module = "org.jetbrains.kotlinx:kotlinx-benchmark-runtime", version.ref = "kotlinx-benchmark" }

dokka-gradlePlugin = "org.jetbrains.dokka:dokka-gradle-plugin:1.9.0"
gradleMavenPublishPlugin = "com.vanniktech:gradle-maven-publish-plugin:0.25.3"
assertk = "com.willowtreeapps.assertk:assertk:0.27.0"
